[package]
name = "visualsign-solana"
version = "0.1.0"
edition = "2024"

[dependencies]

tracing = { workspace = true }
# After https://github.com/tkhq/solana-parser/pull/13 was merged we found that it was looking at files directly, which breaks tests but works in the enclave environment.
solana_parser = { git = "https://github.com/tkhq/solana-parser.git", rev = "1703030a0876b170c299d143247d808e2485a7bf" }
visualsign = { workspace = true }
hex = "0.4.3"
base64 = "0.22.1"
borsh = "1.5.5"
bincode = "1.3.3"
solana-sdk = "2.3"
solana-transaction-status = "2.3"
solana-program = "2.3"
spl-token = "8.0.0"
spl-associated-token-account = "7.0"
spl-stake-pool = "2.0.3"
solana-system-interface = "1.0"
spl-token-2022 = { version = "8.0.0", default-features = false }
spl-token-2022-interface = "1.0.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jupiter-swap-api-client = "0.2.0"
base64 = "0.22.1"
bs58 = "0.5"
